name: Bug report
description: Report a defect with clear reproduction details.
title: "[bug] "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is wrong and why it matters.
      placeholder: Concise defect description.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Numbered steps starting from a clean state.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What happened instead.
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Commit/branch and local environment details.
      placeholder: "main @ <sha>, macOS, Python 3.11, Node 18"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
      description: Remove secrets and sensitive document content before pasting.
